In [24]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [25]:
df = pd.read_csv('BankCustomers.csv')

In [26]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [33]:
data = pd.get_dummies(df, columns = ['Geography','Gender'])
data

RowNumber  CustomerId    Surname  CreditScore  Age  Tenure    Balance  \
0             1    15634602   Hargrave          619   42       2       0.00   
1             2    15647311       Hill          608   41       1   83807.86   
2             3    15619304       Onio          502   42       8  159660.80   
3             4    15701354       Boni          699   39       1       0.00   
4             5    15737888   Mitchell          850   43       2  125510.82   
...         ...         ...        ...          ...  ...     ...        ...   
9995       9996    15606229   Obijiaku          771   39       5       0.00   
9996       9997    15569892  Johnstone          516   35      10   57369.61   
9997       9998    15584532        Liu          709   36       7       0.00   
9998       9999    15682355  Sabbatini          772   42       3   75075.31   
9999      10000    15628319     Walker          792   28       4  130142.79   

      NumOfProducts  HasCrCard  IsActiveMember  EstimatedSalary  Exited  \
0                 1          1               1        101348.88       1   
1                 1          0               1        112542.58       0   
2                 3          1               0        113931.57       1   
3                 2          0               0         93826.63       0   
4                 1          1               1         79084.10       0   
...             ...        ...             ...              ...     ...   
9995              2          1               0         96270.64       0   
9996              1          1               1        101699.77       0   
9997              1          0               1         42085.58       1   
9998              2          1               0         92888.52       1   
9999              1          1               0         38190.78       0   

      Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                    1                  0                0              1   
1                    0                  0                1              1   
2                    1                  0                0              1   
3                    1                  0                0              1   
4                    0                  0                1              1   
...                ...                ...              ...            ...   
9995                 1                  0                0              0   
9996                 1                  0                0              0   
9997                 1                  0                0              1   
9998                 0                  1                0              0   
9999                 1                  0                0              1   

      Gender_Male  
0               0  
1               0  
2               0  
3               0  
4               0  
...           ...  
9995            1  
9996            1  
9997            0  
9998            1  
9999            0  

[10000 rows x 17 columns]

In [35]:
X = data.drop(['RowNumber','CustomerId','Surname','Exited'],axis = 1)
Y = data['Exited']

In [36]:
X

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0             619   42       2       0.00              1          1   
1             608   41       1   83807.86              1          0   
2             502   42       8  159660.80              3          1   
3             699   39       1       0.00              2          0   
4             850   43       2  125510.82              1          1   
...           ...  ...     ...        ...            ...        ...   
9995          771   39       5       0.00              2          1   
9996          516   35      10   57369.61              1          1   
9997          709   36       7       0.00              1          0   
9998          772   42       3   75075.31              2          1   
9999          792   28       4  130142.79              1          1   

      IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0                  1        101348.88                 1                  0   
1                  1        112542.58                 0                  0   
2                  0        113931.57                 1                  0   
3                  0         93826.63                 1                  0   
4                  1         79084.10                 0                  0   
...              ...              ...               ...                ...   
9995               0         96270.64                 1                  0   
9996               1        101699.77                 1                  0   
9997               1         42085.58                 1                  0   
9998               0         92888.52                 0                  1   
9999               0         38190.78                 1                  0   

      Geography_Spain  Gender_Female  Gender_Male  
0                   0              1            0  
1                   1              1            0  
2                   0              1            0  
3                   0              1            0  
4                   1              1            0  
...               ...            ...          ...  
9995                0              0            1  
9996                0              0            1  
9997                0              1            0  
9998                0              0            1  
9999                0              1            0  

[10000 rows x 13 columns]

In [38]:
Y

0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [77]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [78]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [79]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

In [80]:
classifier = Sequential()

In [81]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(activation="relu", input_dim=13, units=8, kernel_initializer="uniform"))

In [82]:
# Adding the second hidden layer
classifier.add(Dense(activation="relu", units=8, kernel_initializer="uniform"))

In [83]:
# Adding the output layer
classifier.add(Dense(activation="sigmoid", units=1, kernel_initializer="uniform"))

In [84]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [85]:
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 2s 276us/step - loss: 0.4854 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 2s 227us/step - loss: 0.4288 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 2s 221us/step - loss: 0.4229 - accuracy: 0.7980
Epoch 4/100
8000/8000 [==============================] - 2s 241us/step - loss: 0.4188 - accuracy: 0.8219
Epoch 5/100
8000/8000 [==============================] - 2s 208us/step - loss: 0.4163 - accuracy: 0.8255
Epoch 6/100
8000/8000 [==============================] - 2s 197us/step - loss: 0.4131 - accuracy: 0.8305
Epoch 7/100
8000/8000 [==============================] - 2s 217us/step - loss: 0.4095 - accuracy: 0.8338
Epoch 8/100
8000/8000 [==============================] - 2s 195us/step - loss: 0.4061 - accuracy: 0.8347
Epoch 9/100
8000/8000 [==============================] - 2s 199us/step - loss: 0.4036 - accuracy: 0.8359
Epoch 10/100
8000/8000 [==============================

8000/8000 [==============================] - 2s 243us/step - loss: 0.3458 - accuracy: 0.8600
Epoch 77/100
8000/8000 [==============================] - 2s 191us/step - loss: 0.3457 - accuracy: 0.8615
Epoch 78/100
8000/8000 [==============================] - 2s 206us/step - loss: 0.3453 - accuracy: 0.8625
Epoch 79/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3450 - accuracy: 0.8626
Epoch 80/100
8000/8000 [==============================] - 1s 185us/step - loss: 0.3446 - accuracy: 0.8604
Epoch 81/100
8000/8000 [==============================] - 2s 203us/step - loss: 0.3442 - accuracy: 0.8611
Epoch 82/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3446 - accuracy: 0.8619
Epoch 83/100
8000/8000 [==============================] - 1s 187us/step - loss: 0.3441 - accuracy: 0.8595
Epoch 84/100
8000/8000 [==============================] - 1s 186us/step - loss: 0.3448 - accuracy: 0.8614
Epoch 85/100
8000/8000 [==============================] - 2

In [86]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [87]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [88]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, y_pred)
accuracy=accuracy_score(y_test,y_pred)

In [89]:
cm

array([[1530,   65],
       [ 206,  199]], dtype=int64)

In [93]:
accuracy*100

86.45

In [94]:
from sklearn.metrics import classification_report 
clf_rep = classification_report(y_test, y_pred)
print(clf_rep)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.49      0.59       405

    accuracy                           0.86      2000
   macro avg       0.82      0.73      0.76      2000
weighted avg       0.86      0.86      0.85      2000



In [96]:
classifier.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_11 (Dense)             (None, 8)                 112       
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_13 (Dense)             (None, 1)                 9         
Total params: 193
Trainable params: 193
Non-trainable params: 0
_________________________________________________________________


In [98]:
from sklearn.ensemble import RandomForestClassifier
randomforestclassifier = RandomForestClassifier(n_estimators=100)
randomforestclassifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [100]:
Y_pred = randomforestclassifier.predict(X_test)
Y_pred = (Y_pred > 0.5)

In [102]:
Y_pred

array([False, False, False, ..., False, False, False])

In [105]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm = confusion_matrix(y_test, Y_pred)
accuracy=accuracy_score(y_test,Y_pred)

In [106]:
cm

array([[1527,   68],
       [ 200,  205]], dtype=int64)

In [107]:
accuracy*100

86.6

In [108]:
from sklearn.metrics import classification_report 
clf_rep = classification_report(y_test, Y_pred)
print(clf_rep)

              precision    recall  f1-score   support

           0       0.88      0.96      0.92      1595
           1       0.75      0.51      0.60       405

    accuracy                           0.87      2000
   macro avg       0.82      0.73      0.76      2000
weighted avg       0.86      0.87      0.86      2000

